[appendix]
[[ch-installation,Installation]]
= Installationsanleitung
(((Installation)))

// == Versionen des Publishers



// == Installation

TIP: Den speedata Publisher kann man in zwei Versionen herunterladen: `stable` und `development`.
Beide Versionen sind problemlos zu benutzen.
Eine umfangreiche Qualitätssicherung verhindert, dass sich unentdeckt Fehler einschleichen.
In der Entwicklungsversion kann die Dokumentation dem aktuellen Stand hinterher sein.
Zum Ausprobieren lädt man sich in der Regel die Development-Version herunter.
Ebenso gibt es den speedata Publisher in zwei Paketen: Standard und Professional.
Die Professional-Variante hat zusätzliche Features, die im professionellen Umfeld für die Druckausgabe hilfreich sind.


Es gibt drei Methoden, den Publisher zu installieren.

. **Binärpakete** (der empfohlene Weg): Auf der https://download.speedata.de/[Download-Seite] (https://download.speedata.de/) sind für macOS, Windows und GNU/Linux ZIP-Dateien zu finden, die man einfach extrahieren kann.
Dafür sind keine Administratorrechte notwendig.
Für Windows gibt es zusätzlich Installationspakete, die den Suchpfad korrekt setzen.
Damit ist in der Windows-Shell das Programm `sp.exe` überall aufrufbar.
 +
 +
Die aus dem ZIP extrahierte Struktur darf nicht verändert werden (z.B. verschieben des Binaries), der speedata Publisher erwartet das vorgegebene Dateilayout.
 +
 +
Nur hier kann das Pro-Paket heruntergeladen werden.

. **APT Repository**: Falls Administratorrechte auf einem Debian oder Ubuntu GNU/Linux System vorhanden sind, kann man einfach die `.deb`-Datei installieren. Hinweis: es wird bis auf weiteres nur die 64-Bit Plattform unterstützt.

.. Erstelle die Datei `/etc/apt/sources.list.d/speedata.list` mit dem Inhalt (Entwicklungsversion - development):
+
-------------------------------------------------------------------------------
deb https://software.speedata.de/download/devel stable main
-------------------------------------------------------------------------------
+
oder für die stabile Version:
+
-------------------------------------------------------------------------------
deb https://software.speedata.de/download/public stable main
-------------------------------------------------------------------------------

.. Füge den GPG-Schlüssel von uns hinzu, damit du sicherstellst, dass du immer die richtige Software bekommst:
+
-------------------------------------------------------------------------------
curl -O http://de.speedata.s3.amazonaws.com/gpgkey-speedata.txt
sudo apt-key add gpgkey-speedata.txt
-------------------------------------------------------------------------------

.. Nun kann man mit  `sudo apt update` und `sudo apt install speedata-publisher` den Publisher installieren.
Die Dokumentation befindet sich in `/usr/share/doc/speedata-publisher/index.html`, die mit `sp doc` auf einem Desktop-System geöffnet werden kann.

. **Aus den Quellen installieren**: Für die Entwickler, die am Publisher selbst Änderungen vornehmen möchten. Hierzu gibt es ein https://hub.docker.com/r/speedata/development[fertiges Docker-Image auf dockerhub]. Alternativ kann man die Software auch lokal bauen: sie aus dem Quellcode gebaut werden mithilfe des Befehls `rake` erstellt werden.
Notwendig dafür sind die üblichen Entwicklungswerkzeuge und die Programmiersprache Go (https://golang.org/) in Version 1.11 oder höher.
Auf einem Debian oder Ubuntu GNU/Linux System kann man folgende Befehle nutzen:
+
-------------------------------------------------------------------------------
sudo apt install build-essential git rake golang
git clone https://github.com/speedata/publisher.git
cd publisher
rake build
rake buildlib
-------------------------------------------------------------------------------
+
Um auch dieses Handbuch bzw. das ebook zu erstellen, wird https://asciidoctor.org/[asciidoctor] benötigt:
+
-------------------------------------------------------------------------------
sudo gem install asciidoctor
rake doc
-------------------------------------------------------------------------------
+
Falls der speedata Publisher aus den Quellen gebaut wird, muss noch [.nowrap]#LuaTeX# hinzugefügt werden.
Der vorgeschlagene Weg ist, unter <https://download.speedata.de/#extra> die Binärpakete zu laden und das passende Paket in das bin-Verzeichnis zu kopieren.
Beispielsweise um LuaTeX 1.15 auf einem Linux AMD64 System zu nutzen, kann man die folgenden Befehle ausführen:
+
-------------------------------------------------------------------------------
wget https://download.speedata.de/files/extra/luatex_115-win-mac-linux.zip
unzip luatex_115-win-mac-linux.zip
cp luatex/linux/sdluatex bin
-------------------------------------------------------------------------------
+
Nach der Installation kann man `bin/sdluatex --version` aufrufen, um zu überprüfen, ob es die richtige Version ist.


TIP: Unter Windows benötigt man die https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads[Microsoft Visual C++ compiler runtime]  und die DLL `VCRuntime140.dll`. Außerdem darf die Installation nicht in einem Verzeichnis liegen, das aus nicht-Ascii Zeichen wie Umlauten besteht.


// EOF