[appendix]
[[ch-filenames,File names with speedata]]
= File name in the Publisher


External files are referenced at various points in the layout, mainly in the images.
These can have the following formats:

* Absolute path in the file system: `/path/to/file.png`.
* Relative path in the file system: `../directory/file.png`.
* File within the search tree: `file.png`. Before starting, the current directory is searched recursively (see <<ch-fileorganization>>).
* Absolute paths under Windows like `c:\Users\...\file.png`.
* file scheme: `file://c/Users/Joe%20User/file.png` or `file:///home/user/file.png`.
* http-scheme: `http://placekitten.com/g/400/300` or https: `https://placekitten.com/g/400/300` (<<ch-speedatapro,Pro feature>>).

These file names can be used for <<cmd-image,Images>>, for <<ch-xpathfunctions,XPath- and layoutfunctions>> as well as on the command line.
So it is possible to start the Publisher with


[source, sh]
-------------------------------------------------------------------------------
sp --dummy --data https://raw.githubusercontent.com/speedata/examples/master/technical/rotating/layout.xml
-------------------------------------------------------------------------------

First the resource is cached on the local computer and then loaded from there.


TIP: Sometimes the backslash (`\`) itself must be provided with a backslash (`\\`). This is mostly necessary at shell level, i.e. when passing arguments when calling the speedata publisher.