[appendix]
[[ch-installation,Installation]]
= Installation instructions
(((Installation)))

TIP: The speedata Publisher can be downloaded in two versions: `stable` and `development`. Both versions are easy to use. Extensive quality assurance prevents errors from creeping in undetected. In the development version, the documentation may be behind the current status. To try it out, you can usually download the development version. The speedata Publisher also comes with a Standard and a Pro plan. The Pro plan offers additional features that are helpful for professional PDF generation.


There are three ways to install speedata Publisher:

. **Binary packages (The recommended way)**: Go to our https://download.speedata.de/[download page] and download the latest package for your operating system. You can unzip the file anywhere in the filesystem you want. You don't need root/administrator rights to use the Publisher this way. There are extra installer packages for windows, if you don't want to set the `PATH` variable yourself. This is the method if you want to install the <<ch-speedatapro,speedata Publisher Pro>> software.


. **APT repository**: If you have root or sudo rights on Debian or Ubuntu GNU/Linux (or a similar system), you can install the .deb files we have prepared from our APT repository. (For now, only the 64 bit architecture is supported.) This is very easy, just follow a few steps:
+
Add our GPG key to the system to make sure you get the correct software:
+
    # all on one line:
    curl -fsSL
       http://de.speedata.s3.amazonaws.com/gpgkey-speedata.txt
       | sudo gpg --dearmor
       -o /usr/share/keyrings/speedata_de.gpg
+
Add the following file to /etc/apt/sources.list.d/speedata.list for the development version (unstable):
+
    deb
      [arch=amd64 signed-by=/usr/share/keyrings/speedata_de.gpg]
      https://software.speedata.de/download/devel stable main
+
or for the main (stable) releases:
+
    deb
       [arch=amd64 signed-by=/usr/share/keyrings/speedata_de.gpg]
       https://software.speedata.de/download/public stable main
+

TIP: The previous three commands and source codes entries must be on one line.

Now you can run `sudo apt update` and `apt install speedata-publisher` and have a working installation.

. **Build from source**: For developers interested in contributing to speedata Publisher, the program and documentation can be built directly from source. You need to have the Go language version 1.21 or later and Lua header files installed. For example, on Debian or Ubuntu GNU/Linux, where Go is packaged as 'golang', you can use the commands:
+
    sudo apt install build-essential git rake golang liblua5.3-dev
    git clone https://github.com/speedata/publisher.git
    cd publisher
    rake build
    rake buildlib
+
If the Lua libraries are in another place than `/usr`, you need to set the environment variable `CGO_CFLAGS` to something like `-I/usr/local/include/lua`. And for Windows you need to also set the `CGO_LDFLAGS` to `-llua53w64 -L/luatex-bin/luatex/windows/amd64/default/` (adjust the path to the LuaTeX binary).
+
To build the manual and the ebook, you need https://asciidoctor.org/[asciidoctor]:
+
-------------------------------------------------------------------------------
sudo gem install asciidoctor
rake doc
-------------------------------------------------------------------------------
+
If you are building speedata Publisher from source, you will also need to install [.nowrap]#LuaTeX# manually. The recommended way is to download a binary from https://download.speedata.de/#extra and copy it into the bin/ directory of the Publisher. For example, to download and install LuaTeX 1.15 on a Linux amd64 system, you could use the commands:
+
    wget https://download.speedata.de/files/extra/luatex_115-win-mac-linux.zip
    unzip luatex_115-win-mac-linux.zip
    cp luatex/linux/sdluatex bin
+
After installation, you can run `bin/sdluatex --version` to confirm the program version.

TIP: On windows, you might need the https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads[Microsoft Visual C++ compiler] and the VCRuntime140.dll. The installation path of the speedata Publisher must only contain ASCII characters and must contain any accented characters.


// EOF