:idprefix: ref-
:leveloffset: +1


ifndef::backend-docbook5[]

[.multicol]
<<cmd-a,A>>  +
<<cmd-action,Action>>  +
<<cmd-addsearchpath,Addsearchpath>>  +
<<cmd-atpagecreation,AtPageCreation>>  +
<<cmd-atpageshipout,AtPageShipout>>  +
<<cmd-attachfile,AttachFile>>  +
<<cmd-attribute,Attribute>>  +
<<cmd-b,B>>  +
<<cmd-barcode,Barcode>>  +
<<cmd-bold,Bold>>  +
<<cmd-bolditalic,BoldItalic>>  +
<<cmd-bookmark,Bookmark>>  +
<<cmd-box,Box>>  +
<<cmd-br,Br>>  +
<<cmd-case,Case>>  +
<<cmd-circle,Circle>>  +
<<cmd-color,Color>>  +
<<cmd-column,Column>>  +
<<cmd-columns,Columns>>  +
<<cmd-compatibility,Compatibility>>  +
<<cmd-contents,Contents>>  +
<<cmd-copy_of,Copy-of>>  +
<<cmd-definecolor,DefineColor>>  +
<<cmd-definecolorprofile,DefineColorprofile>>  +
<<cmd-definefontalias,DefineFontalias>>  +
<<cmd-definefontfamily,DefineFontfamily>>  +
<<cmd-definematter,DefineMatter>>  +
<<cmd-definetextformat,DefineTextformat>>  +
<<cmd-element,Element>>  +
<<cmd-fallback,Fallback>>  +
<<cmd-fontface,Fontface>>  +
<<cmd-forall,ForAll>>  +
<<cmd-frame,Frame>>  +
<<cmd-grid,Grid>>  +
<<cmd-group,Group>>  +
<<cmd-groupcontents,Groupcontents>>  +
<<cmd-hspace,HSpace>>  +
<<cmd-hyphenation,Hyphenation>>  +
<<cmd-i,I>>  +
<<cmd-image,Image>>  +
<<cmd-include,Include>>  +
<<cmd-initial,Initial>>  +
<<cmd-insertpages,InsertPages>>  +
<<cmd-italic,Italic>>  +
<<cmd-layout,Layout>>  +
<<cmd-li,Li>>  +
<<cmd-loaddataset,LoadDataset>>  +
<<cmd-loadfontfile,LoadFontfile>>  +
<<cmd-loop,Loop>>  +
<<cmd-makeindex,Makeindex>>  +
<<cmd-margin,Margin>>  +
<<cmd-mark,Mark>>  +
<<cmd-message,Message>>  +
<<cmd-newpage,NewPage>>  +
<<cmd-nextframe,NextFrame>>  +
<<cmd-nextrow,NextRow>>  +
<<cmd-nobreak,NoBreak>>  +
<<cmd-ol,Ol>>  +
<<cmd-options,Options>>  +
<<cmd-otherwise,Otherwise>>  +
<<cmd-output,Output>>  +
<<cmd-overlay,Overlay>>  +
<<cmd-pageformat,Pageformat>>  +
<<cmd-pagetype,Pagetype>>  +
<<cmd-paragraph,Paragraph>>  +
<<cmd-pdfoptions,PDFOptions>>  +
<<cmd-placeobject,PlaceObject>>  +
<<cmd-position,Position>>  +
<<cmd-positioningarea,PositioningArea>>  +
<<cmd-positioningframe,PositioningFrame>>  +
<<cmd-processnode,ProcessNode>>  +
<<cmd-record,Record>>  +
<<cmd-regular,Regular>>  +
<<cmd-rule,Rule>>  +
<<cmd-savedataset,SaveDataset>>  +
<<cmd-savepages,SavePages>>  +
<<cmd-setgrid,SetGrid>>  +
<<cmd-setvariable,SetVariable>>  +
<<cmd-sortsequence,SortSequence>>  +
<<cmd-stylesheet,Stylesheet>>  +
<<cmd-span,Span>>  +
<<cmd-sub,Sub>>  +
<<cmd-sup,Sup>>  +
<<cmd-switch,Switch>>  +
<<cmd-table,Table>>  +
<<cmd-tablefoot,Tablefoot>>  +
<<cmd-tablenewpage,TableNewPage>>  +
<<cmd-tablehead,Tablehead>>  +
<<cmd-tablerule,Tablerule>>  +
<<cmd-td,Td>>  +
<<cmd-text,Text>>  +
<<cmd-textblock,Textblock>>  +
<<cmd-tr,Tr>>  +
<<cmd-trace,Trace>>  +
<<cmd-transformation,Transformation>>  +
<<cmd-u,U>>  +
<<cmd-ul,Ul>>  +
<<cmd-until,Until>>  +
<<cmd-url,URL>>  +
<<cmd-value,Value>>  +
<<cmd-vspace,VSpace>>  +
<<cmd-while,While>>  +
endif::[]


include::ref/a.adoc[]

== See also

The section <<ch-textformatting>>.

include::ref/action.adoc[]

== See also

The command <<cmd-mark,`<Mark>`>> and the section <<ch-directories-marker>>


include::ref/addsearchpath.adoc[]

== See also


include::ref/atpagecreation.adoc[]

== See also

Commands <<cmd-atpageshipout,`<AtPageShipout>`>> and <<cmd-pagetype,`<Pagetype>`>> as well as the section <<ch-pagetypes>>.


include::ref/atpageshipout.adoc[]

== See also

Commands <<cmd-atpagecreation,`<AtPageCreation>`>> and <<cmd-pagetype,`<Pagetype>`>> as well as the section <<ch-pagetypes>>.

include::ref/attachfile.adoc[]

== See also


include::ref/attribute.adoc[]

== See also

Commands <<cmd-element,`<Element>`>>, <<cmd-loaddataset,`<LoadDataset>`>> and <<cmd-savedataset,`<SaveDataset>`>> as well as the section <<ch-elementattribute>>.


include::ref/b.adoc[]

== See also

The section <<ch-textformatting,text formatting>> as well as the commands <<cmd-i,`<I>`>> and <<cmd-u,`<U>`>>.

include::ref/barcode.adoc[]

== See also

The section about <<ch-barcodes,`<Barcodes>` in the basics chapter>>.


include::ref/bold.adoc[]

== See also

Command <<cmd-definefontfamily,`<DefineFontfamily>`>>, chapter <<ch-fonts>>.


include::ref/bolditalic.adoc[]

== See also

Command <<cmd-definefontfamily,`<DefineFontfamily>`>>, chapter <<ch-fonts>>.

include::ref/bookmark.adoc[]

== See also

Chapter <<ch-bookmarks,about bookmarks>>.

include::ref/box.adoc[]

== See also

The section about <<ch-outputtingobjects-box,`<Box>` in the basics chapter>>.

include::ref/br.adoc[]

== See also

The section <<ch-textformatting,text formatting>>.

include::ref/case.adoc[]

== See also

The section <<ch-programming-case,programming>>.


include::ref/circle.adoc[]

== See also

The section about <<ch-outputtingobjects-circle,`<Circle>` in the basics chapter>>.

include::ref/color.adoc[]

== See also

The section <<ch-textformatting,text formatting>>, the section <<ch-colors,about colors>> and the command <<cmd-definecolor,`<DefineColor>`>>.

include::ref/column.adoc[]

== See also

The section about <<ch-tables-columnwidths,Columns>> in chapter <<ch-tables2>>.


include::ref/columns.adoc[]

== See also

The section about <<ch-tables-columnwidths,Columns>> in chapter <<ch-tables2>>.


include::ref/compatibility.adoc[]
include::ref/contents.adoc[]

== See also

The command <<cmd-group,<Group>>> and the section about <<ch-groups>>.

include::ref/copy-of.adoc[]

== See also

The section about <<ch-copyof,`<Copy-of>`>>.

include::ref/definecolor.adoc[]

== See also

The section about <<ch-colors,colors>>.

include::ref/definecolorprofile.adoc[]

== See also

The section about <<ch-colors,colors>>.

include::ref/definefontalias.adoc[]

== See also

The section about <<ch-fonts>> and the command <<cmd-definefontfamily,`<DefineFontfamily>`>> as well as <<cmd-loadfontfile,`<LoadFontfile>`>>.

include::ref/definefontfamily.adoc[]

== See also

The section about <<ch-fonts>> and the command <<cmd-definefontalias,`<DefineFontalias>`>> as well as <<cmd-loadfontfile,`<LoadFontfile>`>>.

include::ref/definematter.adoc[]

== See also

The command <<cmd-pageformat>>.


include::ref/definetextformat.adoc[]

== See also

The section about <<ch-textformats>>.

include::ref/element.adoc[]

== See also

Commands <<cmd-attribute,`<Attribute>`>>, <<cmd-loaddataset,`<LoadDataset>`>> and <<cmd-savedataset,`SaveDataset`>> as well as the section <<ch-elementattribute>>.

include::ref/fallback.adoc[]

== See also

Command <<cmd-loadfontfile,`<LoadFontfile>`>>, chapter <<ch-fonts>>.


include::ref/fontface.adoc[]

== See also

The section <<ch-textformatting,text formatting>>.


include::ref/forall.adoc[]

== See also

The section about <<ch-structuredatafile>>.

include::ref/frame.adoc[]

== See also

The section about <<ch-outputtingobjects-frame,frames in the basics chapter>>.

include::ref/grid.adoc[]

== See also

The section about <<ch-grid,grids>> and the section about <<ch-groups>>.


include::ref/group.adoc[]

== See also

The section about <<ch-groups>>.

include::ref/groupcontents.adoc[]

== See also

The section about <<ch-groups>>.


include::ref/hspace.adoc[]

== See also

The section <<ch-textformatting,text formatting>>.

// include::ref/html.adoc[]

// == See also

// The examples repository at https://github.com/speedata/examples/tree/master/technical/html

include::ref/hyphenation.adoc[]

== See also

The section <<ch-hyphenation-language>>.

include::ref/i.adoc[]

== See also

The section <<ch-textformatting,text formatting>> as well as the commands <<cmd-b,`<B>`>> and <<cmd-u,`<U>`>>.

include::ref/image.adoc[]

== See also

The section about <<ch-outputtingobjects-images,`<Image>` in the basics chapter>>, <<ch-fileorganization>>


include::ref/include.adoc[]

== See also

The section about <<ch-splitlayout>>.


include::ref/initial.adoc[]

== See also




include::ref/insertpages.adoc[]


== See also

The command <<cmd-savepages,`<SavePages>`>>, the section <<ch-savepages>> and <<ch-cookbook-tocinonerun>>.


include::ref/italic.adoc[]

== See also

Command <<cmd-definefontfamily,`<DefineFontfamily>`>>, chapter <<ch-fonts>>.

include::ref/layout.adoc[]

== See also

include::ref/li.adoc[]

== See also

The section <<ch-textformatting-enumerationlists>> as well as the commands <<cmd-ol,`<Ol>`>> and <<cmd-ul,`<Ul>`>>.

include::ref/loaddataset.adoc[]

== See also

Commands <<cmd-element,`<Element>`>>, <<cmd-attribute,`<Attribute>`>> and <<cmd-savedataset,`<SaveDataset>`>> as well as the section <<ch-elementattribute>>.

include::ref/loadfontfile.adoc[]

== See also

Command <<cmd-definefontfamily,`<DefineFontfamily>`>>, chapter <<ch-fonts>>.


include::ref/loop.adoc[]

== See also

The section <<ch-programming-loops,programming>>.

include::ref/makeindex.adoc[]

== See also

The section <<ch-indexcreation>>.


include::ref/margin.adoc[]

== See also

The command <<cmd-pagetype,`<Pagetype>`>>, the section <<ch-pagetypes>>.

include::ref/mark.adoc[]

== See also

The command <<cmd-action,`<Action>`>> and the section <<ch-directories-marker>>.

include::ref/message.adoc[]

== See also

The section <<ch-troubleshooting>>.

include::ref/newpage.adoc[]

== See also

<<ch-pagetypes-newpage>>


include::ref/nextframe.adoc[]

== See also

The section <<ch-positioningframe-nextframe>> in chapter about positioning frames.


include::ref/nextrow.adoc[]

== See also

The section <<ch-cursor,Cursor>> in chapter about positioning frames.


include::ref/nobreak.adoc[]

== See also

The section <<ch-textformatting-nobreak>> in the basics chapter.



include::ref/ol.adoc[]

== See also

The section <<ch-textformatting-enumerationlists>> as well as the commands <<cmd-li,`<Li>`>> and <<cmd-ul,`<Ul>`>>.


include::ref/options.adoc[]
== See also

<<ch-commandline>>, <<ch-configuration>>.

include::ref/otherwise.adoc[]

== See also

The section <<ch-programming-case,programming>>.


include::ref/output.adoc[]

== See also

The command <<ch-outputobjects-output,`<Text>` in the basics chapter>>.



include::ref/overlay.adoc[]
== See also

The section <<ch-tables-imagebehindtext>> in chapter about tables.


include::ref/pageformat.adoc[]

== See also

The section <<ch-outputforprinter>>.


include::ref/pagetype.adoc[]

== See also

The section <<ch-pagetypes>> and the command <<cmd-definematter>>.


include::ref/paragraph.adoc[]
== See also

The section <<ch-textformatting,text formatting>> and the command <<cmd-options>> for a list of all languages.



include::ref/pdfoptions.adoc[]

== See also

The section <<ch-outputforprinter>>.


include::ref/placeobject.adoc[]

== See also

The detailed description in <<ch-outputtingobjects>>.


include::ref/position.adoc[]

== See also

The section <<ch-tables-imagebehindtext>> in chapter about tables.

include::ref/positioningarea.adoc[]

== See also

The section <<ch-positioningarea>>.


include::ref/positioningframe.adoc[]
== See also

The section <<ch-positioningarea>>.


include::ref/processnode.adoc[]

== See also

The section about <<ch-structuredatafile>>.

include::ref/record.adoc[]

== See also

The section about <<ch-structuredatafile>>.

include::ref/regular.adoc[]

== See also

Command <<cmd-definefontfamily,`<DefineFontfamily>`>>, chapter <<ch-fonts>>.


include::ref/rule.adoc[]

== See also

The section about <<ch-outputtingobjects-rules,rules in the basics chapter>>.

include::ref/savedataset.adoc[]

== See also

Commands <<cmd-attribute,`<Attribute>`>>, <<cmd-element,`<Element>`>> and <<cmd-loaddataset,`<LoadDataset>`>> as well as the section <<ch-elementattribute>>.


include::ref/savepages.adoc[]
== See also

The command <<cmd-insertpages,`<InsertPages>`>>, the section <<ch-savepages>> and <<ch-cookbook-tocinonerun>>.

include::ref/setgrid.adoc[]

== See also

The section about <<ch-grid,page grids>>.

include::ref/setvariable.adoc[]

== See also

The section <<ch-programming>>


include::ref/sortsequence.adoc[]

== See also

The section <<ch-sortingdata>>.

include::ref/stylesheet.adoc[]

== See also

The section <<ch-css,about CSS>>.

include::ref/span.adoc[]

== See also

The command <<cmd-options>> for a list of all languages.

include::ref/sub.adoc[]

== See also

The section <<ch-textformatting,text formatting>> as well as the command <<cmd-sup,`<Sup>`>>

include::ref/sup.adoc[]

== See also

The section <<ch-textformatting,text formatting>> as well as the command <<cmd-sub,`<Sub>`>>

include::ref/switch.adoc[]

== See also

The section <<ch-programming-case,programming>>.


include::ref/table.adoc[]

== See also

The section <<ch-tables2,tables>>.

include::ref/tablenewpage.adoc[]
== See also

Command <<cmd-table,`<Table>`>>, <<ch-tables2,chapter about tables>>.


include::ref/tablefoot.adoc[]
== See also

Command <<cmd-table,`<Table>`>>, <<ch-tables2,chapter about tables>>.

include::ref/tablehead.adoc[]
== See also

Command <<cmd-table,`<Table>`>>, <<ch-tables2,chapter about tables>>.

include::ref/tablerule.adoc[]
== See also

Command <<cmd-table,`<Table>`>>, <<ch-tables2,chapter about tables>>.

include::ref/td.adoc[]
== See also

Command <<cmd-table,`<Table>`>>, <<ch-tables2,chapter about tables>>.

include::ref/text.adoc[]

== See also

The command <<ch-outputobjects-output,`<Text>` in the basics chapter>>.

include::ref/textblock.adoc[]

== See also

The command <<ch-outputtingobjects-textblock,`<Textblock>` in the basics chapter>>.

include::ref/tr.adoc[]

== See also

Command <<cmd-table,<Table>>>, <<ch-tables2,chapter about tables>>.

include::ref/trace.adoc[]

== See also

The section <<ch-troubleshooting>>.


include::ref/transformation.adoc[]

== See also

The section about <<ch-outputtingobjects-transformation,`<Transformation>` in the basics chapter>>.

include::ref/u.adoc[]

== See also

The section <<ch-textformatting,text formatting>> as well as the commands <<cmd-b,`<B>`>> and <<cmd-i,`<I>`>>.

include::ref/ul.adoc[]

== See also

The section <<ch-textformatting-enumerationlists>> as well as the commands <<cmd-li,`<Li>`>> and <<cmd-ol,`<Ol>`>>.


include::ref/until.adoc[]

== See also

The section <<ch-programming-loops,loops>> in chapter programming.

include::ref/url.adoc[]


== See also

The section about <<ch-textformatting-url>> in chapter about text formatting.


include::ref/value.adoc[]
include::ref/vspace.adoc[]

== See also

The section <<ch-tables2-cellsandrows,table cells and rows>> in chapter tables.


include::ref/while.adoc[]

== See also

The section <<ch-programming-loops,loops>> in chapter programming.


:leveloffset: -1
