-- Operator dictionary for the MathML walker (src/lua/publisher/math.lua).
-- Maps a Unicode code point to its math class. Code points not listed are
-- ordinary atoms.
--
-- Generated from unicode-math-table.tex of the LaTeX package unicode-math
-- (LPPL 1.3c) by src/lua/tools/genmathoperators.lua. Do not edit; run
-- "rake mathoperators" to regenerate.
--
-- Classes: bin, rel, open, close, punct, op (large operator, limits in
-- display style), opnolimits (integral-like, limits always as scripts),
-- fence (vertical bars), accent, botaccent, over, under.
return {
    [0x0021] = "close", -- exclamation mark
    [0x0028] = "open", -- left parenthesis
    [0x0029] = "close", -- right parenthesis
    [0x002B] = "bin", -- plus sign b:
    [0x002C] = "punct", -- comma
    [0x003A] = "punct", -- colon
    [0x003B] = "punct", -- semicolon p:
    [0x003C] = "rel", -- less-than sign r:
    [0x003D] = "rel", -- equals sign r:
    [0x003E] = "rel", -- greater-than sign r:
    [0x005B] = "open", -- left square bracket
    [0x005D] = "close", -- right square bracket
    [0x007B] = "open", -- left curly bracket
    [0x007C] = "fence", -- vertical bar
    [0x007D] = "close", -- right curly bracket
    [0x00B1] = "bin", -- plus-or-minus sign
    [0x00B7] = "bin", -- /centerdot b: middle dot
    [0x00D7] = "bin", -- multiply sign
    [0x00F7] = "bin", -- divide sign
    [0x0300] = "accent", -- grave accent
    [0x0301] = "accent", -- acute accent
    [0x0302] = "accent", -- circumflex accent
    [0x0303] = "accent", -- tilde
    [0x0304] = "accent", -- macron
    [0x0305] = "accent", -- overbar embellishment
    [0x0306] = "accent", -- breve
    [0x0307] = "accent", -- dot above
    [0x0308] = "accent", -- dieresis
    [0x0309] = "accent", -- combining hook above
    [0x030A] = "accent", -- ring
    [0x030C] = "accent", -- caron
    [0x0310] = "accent", -- candrabindu (non-spacing)
    [0x0312] = "accent", -- combining turned comma above
    [0x0315] = "accent", -- combining comma above right
    [0x031A] = "accent", -- left angle above (non-spacing)
    [0x0330] = "botaccent", -- under tilde accent (multiple characters and non-spacing)
    [0x0332] = "botaccent", -- combining low line
    [0x0338] = "accent", -- combining long solidus overlay
    [0x034D] = "botaccent", -- underleftrightarrow accent
    [0x2016] = "fence", -- double vertical bar
    [0x2020] = "bin", -- dagger relation
    [0x2021] = "bin", -- double dagger relation
    [0x2022] = "bin", -- /bullet b: round bullet, filled
    [0x2040] = "bin", -- character tie, z notation sequence concatenation
    [0x2044] = "bin", -- fraction slash
    [0x2050] = "rel", -- close up
    [0x20D0] = "accent", -- combining left harpoon above
    [0x20D1] = "accent", -- combining right harpoon above
    [0x20D2] = "accent", -- combining long vertical line overlay
    [0x20D6] = "accent", -- combining left arrow above
    [0x20D7] = "accent", -- combining left arrow above
    [0x20DB] = "accent", -- combining three dots above
    [0x20DC] = "accent", -- combining four dots above
    [0x20E1] = "accent", -- combining left right arrow above
    [0x20E7] = "accent", -- combining annuity symbol
    [0x20E8] = "botaccent", -- combining triple underdot
    [0x20E9] = "accent", -- combining wide bridge above
    [0x20EC] = "botaccent", -- combining rightwards harpoon with barb downwards
    [0x20ED] = "botaccent", -- combining leftwards harpoon with barb downwards
    [0x20EE] = "botaccent", -- combining left arrow below
    [0x20EF] = "botaccent", -- combining right arrow below
    [0x20F0] = "accent", -- combining asterisk above
    [0x2140] = "op", -- double-struck n-ary summation
    [0x214B] = "bin", -- turned ampersand
    [0x2190] = "rel", -- /leftarrow /gets a: leftward arrow
    [0x2191] = "rel", -- upward arrow
    [0x2192] = "rel", -- /rightarrow /to a: rightward arrow
    [0x2193] = "rel", -- downward arrow
    [0x2194] = "rel", -- left and right arrow
    [0x2195] = "rel", -- up and down arrow
    [0x2196] = "rel", -- nw pointing arrow
    [0x2197] = "rel", -- ne pointing arrow
    [0x2198] = "rel", -- se pointing arrow
    [0x2199] = "rel", -- sw pointing arrow
    [0x219A] = "rel", -- not left arrow
    [0x219B] = "rel", -- not right arrow
    [0x219C] = "rel", -- left arrow-wavy
    [0x219D] = "rel", -- right arrow-wavy
    [0x219E] = "rel", -- left two-headed arrow
    [0x219F] = "rel", -- up two-headed arrow
    [0x21A0] = "rel", -- right two-headed arrow
    [0x21A1] = "rel", -- down two-headed arrow
    [0x21A2] = "rel", -- left arrow-tailed
    [0x21A3] = "rel", -- right arrow-tailed
    [0x21A4] = "rel", -- maps to, leftward
    [0x21A5] = "rel", -- maps to, upward
    [0x21A6] = "rel", -- maps to, rightward
    [0x21A7] = "rel", -- maps to, downward
    [0x21A9] = "rel", -- left arrow-hooked
    [0x21AA] = "rel", -- right arrow-hooked
    [0x21AB] = "rel", -- left arrow-looped
    [0x21AC] = "rel", -- right arrow-looped
    [0x21AD] = "rel", -- left and right arr-wavy
    [0x21AE] = "rel", -- not left and right arrow
    [0x21AF] = "rel", -- downwards zigzag arrow
    [0x21B0] = "rel", -- /lsh a:
    [0x21B1] = "rel", -- /rsh a:
    [0x21B2] = "rel", -- left down angled arrow
    [0x21B3] = "rel", -- right down angled arrow
    [0x21B6] = "rel", -- left curved arrow
    [0x21B7] = "rel", -- right curved arrow
    [0x21BC] = "rel", -- left harpoon-up
    [0x21BD] = "rel", -- left harpoon-down
    [0x21BE] = "rel", -- /upharpoonright /restriction a: up harpoon-right
    [0x21BF] = "rel", -- up harpoon-left
    [0x21C0] = "rel", -- right harpoon-up
    [0x21C1] = "rel", -- right harpoon-down
    [0x21C2] = "rel", -- down harpoon-right
    [0x21C3] = "rel", -- down harpoon-left
    [0x21C4] = "rel", -- right arrow over left arrow
    [0x21C5] = "rel", -- up arrow, down arrow
    [0x21C6] = "rel", -- left arrow over right arrow
    [0x21C7] = "rel", -- two left arrows
    [0x21C8] = "rel", -- two up arrows
    [0x21C9] = "rel", -- two right arrows
    [0x21CA] = "rel", -- two down arrows
    [0x21CB] = "rel", -- left harpoon over right
    [0x21CC] = "rel", -- right harpoon over left
    [0x21CD] = "rel", -- not implied by
    [0x21CE] = "rel", -- not left and right double arrows
    [0x21CF] = "rel", -- not implies
    [0x21D0] = "rel", -- is implied by
    [0x21D1] = "rel", -- up double arrow
    [0x21D2] = "rel", -- implies
    [0x21D3] = "rel", -- down double arrow
    [0x21D4] = "rel", -- left and right double arrow
    [0x21D5] = "rel", -- up and down double arrow
    [0x21D6] = "rel", -- nw pointing double arrow
    [0x21D7] = "rel", -- ne pointing double arrow
    [0x21D8] = "rel", -- se pointing double arrow
    [0x21D9] = "rel", -- sw pointing double arrow
    [0x21DA] = "rel", -- left triple arrow
    [0x21DB] = "rel", -- right triple arrow
    [0x21DC] = "rel", -- leftwards squiggle arrow
    [0x21DD] = "rel", -- rightwards squiggle arrow
    [0x21E4] = "rel", -- leftwards arrow to bar
    [0x21E5] = "rel", -- rightwards arrow to bar
    [0x21F4] = "rel", -- right arrow with small circle
    [0x21F5] = "rel", -- downwards arrow leftwards of upwards arrow
    [0x21F6] = "rel", -- three rightwards arrows
    [0x21F7] = "rel", -- leftwards arrow with vertical stroke
    [0x21F8] = "rel", -- rightwards arrow with vertical stroke
    [0x21F9] = "rel", -- left right arrow with vertical stroke
    [0x21FA] = "rel", -- leftwards arrow with double vertical stroke
    [0x21FB] = "rel", -- rightwards arrow with double vertical stroke
    [0x21FC] = "rel", -- left right arrow with double vertical stroke
    [0x21FD] = "rel", -- leftwards open-headed arrow
    [0x21FE] = "rel", -- rightwards open-headed arrow
    [0x21FF] = "rel", -- left right open-headed arrow
    [0x2208] = "rel", -- set membership, variant
    [0x2209] = "rel", -- negated set membership
    [0x220A] = "rel", -- set membership (small set membership)
    [0x220B] = "rel", -- contains, variant
    [0x220C] = "rel", -- negated contains, variant
    [0x220D] = "rel", -- /ni /owns r: contains (small contains as member)
    [0x220F] = "op", -- product operator
    [0x2210] = "op", -- coproduct operator
    [0x2211] = "op", -- summation operator
    [0x2212] = "bin", -- minus sign
    [0x2213] = "bin", -- minus-or-plus sign
    [0x2214] = "bin", -- plus sign, dot above
    [0x2215] = "bin", -- division slash
    [0x2216] = "bin", -- small set minus (cf. reverse solidus)
    [0x2217] = "bin", -- centered asterisk
    [0x2218] = "bin", -- composite function (small circle)
    [0x2219] = "bin", -- bullet operator
    [0x221B] = "open", -- cube root
    [0x221C] = "open", -- fourth root
    [0x221D] = "rel", -- is proportional to
    [0x2223] = "rel", -- /mid r:
    [0x2224] = "rel", -- negated mid
    [0x2225] = "rel", -- parallel
    [0x2226] = "rel", -- not parallel
    [0x2227] = "bin", -- /wedge /land b: logical and
    [0x2228] = "bin", -- /vee /lor b: logical or
    [0x2229] = "bin", -- intersection
    [0x222A] = "bin", -- union or logical sum
    [0x222B] = "opnolimits", -- integral operator
    [0x222C] = "opnolimits", -- double integral operator
    [0x222D] = "opnolimits", -- triple integral operator
    [0x222E] = "opnolimits", -- contour integral operator
    [0x222F] = "opnolimits", -- double contour integral operator
    [0x2230] = "opnolimits", -- triple contour integral operator
    [0x2231] = "opnolimits", -- clockwise integral
    [0x2232] = "opnolimits", -- contour integral, clockwise
    [0x2233] = "opnolimits", -- contour integral, anticlockwise
    [0x2236] = "rel", -- ratio
    [0x2237] = "rel", -- two colons
    [0x2238] = "bin", -- minus sign, dot above
    [0x2239] = "rel", -- excess (-:)
    [0x223A] = "rel", -- minus with four dots, geometric properties
    [0x223B] = "rel", -- homothetic
    [0x223C] = "rel", -- similar
    [0x223D] = "rel", -- reverse similar
    [0x223E] = "bin", -- most positive [inverted lazy s]
    [0x2240] = "bin", -- wreath product
    [0x2241] = "rel", -- not similar
    [0x2242] = "rel", -- equals, similar
    [0x2243] = "rel", -- similar, equals
    [0x2244] = "rel", -- not similar, equals
    [0x2245] = "rel", -- congruent with
    [0x2246] = "rel", -- similar, not equals [vert only for 9573 entity]
    [0x2247] = "rel", -- not congruent with
    [0x2248] = "rel", -- approximate
    [0x2249] = "rel", -- not approximate
    [0x224A] = "rel", -- approximate, equals
    [0x224B] = "rel", -- approximately identical to
    [0x224C] = "rel", -- all equal to
    [0x224D] = "rel", -- asymptotically equal to
    [0x224E] = "rel", -- bumpy equals
    [0x224F] = "rel", -- bumpy equals, equals
    [0x2250] = "rel", -- equals, single dot above
    [0x2251] = "rel", -- /doteqdot /doteq r: equals, even dots
    [0x2252] = "rel", -- equals, falling dots
    [0x2253] = "rel", -- equals, rising dots
    [0x2254] = "rel", -- colon, equals
    [0x2255] = "rel", -- equals, colon
    [0x2256] = "rel", -- circle on equals sign
    [0x2257] = "rel", -- circle, equals
    [0x2258] = "rel", -- arc, equals; corresponds to
    [0x2259] = "rel", -- corresponds to (wedge, equals)
    [0x225A] = "rel", -- logical or, equals
    [0x225B] = "rel", -- star equals
    [0x225C] = "rel", -- triangle, equals
    [0x225D] = "rel", -- equals by definition
    [0x225E] = "rel", -- measured by (m over equals)
    [0x225F] = "rel", -- equal with questionmark
    [0x2260] = "rel", -- /ne /neq r: not equal
    [0x2261] = "rel", -- identical with
    [0x2262] = "rel", -- not identical with
    [0x2263] = "rel", -- strict equivalence (4 lines)
    [0x2264] = "rel", -- /leq /le r: less-than-or-equal
    [0x2265] = "rel", -- /geq /ge r: greater-than-or-equal
    [0x2266] = "rel", -- less, double equals
    [0x2267] = "rel", -- greater, double equals
    [0x2268] = "rel", -- less, not double equals
    [0x2269] = "rel", -- greater, not double equals
    [0x226A] = "rel", -- much less than, type 2
    [0x226B] = "rel", -- much greater than, type 2
    [0x226C] = "rel", -- between
    [0x226D] = "rel", -- not asymptotically equal to
    [0x226E] = "rel", -- not less-than
    [0x226F] = "rel", -- not greater-than
    [0x2270] = "rel", -- not less-than-or-equal
    [0x2271] = "rel", -- not greater-than-or-equal
    [0x2272] = "rel", -- less, similar
    [0x2273] = "rel", -- greater, similar
    [0x2274] = "rel", -- not less, similar
    [0x2275] = "rel", -- not greater, similar
    [0x2276] = "rel", -- less, greater
    [0x2277] = "rel", -- greater, less
    [0x2278] = "rel", -- not less, greater
    [0x2279] = "rel", -- not greater, less
    [0x227A] = "rel", -- precedes
    [0x227B] = "rel", -- succeeds
    [0x227C] = "rel", -- precedes, curly equals
    [0x227D] = "rel", -- succeeds, curly equals
    [0x227E] = "rel", -- precedes, similar
    [0x227F] = "rel", -- succeeds, similar
    [0x2280] = "rel", -- not precedes
    [0x2281] = "rel", -- not succeeds
    [0x2282] = "rel", -- subset or is implied by
    [0x2283] = "rel", -- superset or implies
    [0x2284] = "rel", -- not subset, variant [slash negation]
    [0x2285] = "rel", -- not superset, variant [slash negation]
    [0x2286] = "rel", -- subset, equals
    [0x2287] = "rel", -- superset, equals
    [0x2288] = "rel", -- not subset, equals
    [0x2289] = "rel", -- not superset, equals
    [0x228A] = "rel", -- subset, not equals
    [0x228B] = "rel", -- superset, not equals
    [0x228C] = "bin", -- multiset
    [0x228D] = "bin", -- union, with dot
    [0x228E] = "bin", -- plus sign in union
    [0x228F] = "rel", -- square subset
    [0x2290] = "rel", -- square superset
    [0x2291] = "rel", -- square subset, equals
    [0x2292] = "rel", -- square superset, equals
    [0x2293] = "bin", -- square intersection
    [0x2294] = "bin", -- square union
    [0x2295] = "bin", -- plus sign in circle
    [0x2296] = "bin", -- minus sign in circle
    [0x2297] = "bin", -- multiply sign in circle
    [0x2298] = "bin", -- solidus in circle
    [0x2299] = "bin", -- middle dot in circle
    [0x229A] = "bin", -- small circle in circle
    [0x229B] = "bin", -- asterisk in circle
    [0x229C] = "bin", -- equal in circle
    [0x229D] = "bin", -- hyphen in circle
    [0x229E] = "bin", -- plus sign in box
    [0x229F] = "bin", -- minus sign in box
    [0x22A0] = "bin", -- multiply sign in box
    [0x22A1] = "bin", -- /dotsquare /boxdot b: small dot in box
    [0x22A2] = "rel", -- vertical, dash
    [0x22A3] = "rel", -- dash, vertical
    [0x22A6] = "rel", -- assertion (vertical, short dash)
    [0x22A7] = "rel", -- models (vertical, short double dash)
    [0x22A8] = "rel", -- vertical, double dash
    [0x22A9] = "rel", -- double vertical, dash
    [0x22AA] = "rel", -- triple vertical, dash
    [0x22AB] = "rel", -- double vert, double dash
    [0x22AC] = "rel", -- not vertical, dash
    [0x22AD] = "rel", -- not vertical, double dash
    [0x22AE] = "rel", -- not double vertical, dash
    [0x22AF] = "rel", -- not double vert, double dash
    [0x22B0] = "rel", -- element precedes under relation
    [0x22B1] = "rel", -- succeeds under relation
    [0x22B2] = "rel", -- left triangle, open, variant
    [0x22B3] = "rel", -- right triangle, open, variant
    [0x22B4] = "rel", -- left triangle, equals
    [0x22B5] = "rel", -- right triangle, equals
    [0x22B6] = "rel", -- original of
    [0x22B7] = "rel", -- image of
    [0x22B8] = "rel", -- /multimap a:
    [0x22BA] = "bin", -- intercal
    [0x22BB] = "bin", -- logical or, bar below (large vee); exclusive disjunction
    [0x22BC] = "bin", -- bar, wedge (large wedge)
    [0x22BD] = "bin", -- bar, vee (large vee)
    [0x22C0] = "op", -- logical and operator
    [0x22C1] = "op", -- logical or operator
    [0x22C2] = "op", -- intersection operator
    [0x22C3] = "op", -- union operator
    [0x22C4] = "bin", -- white diamond
    [0x22C5] = "bin", -- small middle dot
    [0x22C6] = "bin", -- small star, filled, low
    [0x22C7] = "bin", -- division on times
    [0x22C8] = "rel", -- bowtie
    [0x22C9] = "bin", -- times sign, left closed
    [0x22CA] = "bin", -- times sign, right closed
    [0x22CB] = "bin", -- left semidirect product
    [0x22CC] = "bin", -- right semidirect product
    [0x22CD] = "rel", -- reverse similar, equals
    [0x22CE] = "bin", -- curly logical or
    [0x22CF] = "bin", -- curly logical and
    [0x22D0] = "rel", -- double subset
    [0x22D1] = "rel", -- double superset
    [0x22D2] = "bin", -- /cap /doublecap b: double intersection
    [0x22D3] = "bin", -- /cup /doublecup b: double union
    [0x22D4] = "rel", -- pitchfork
    [0x22D5] = "rel", -- parallel, equal; equal or parallel
    [0x22D6] = "rel", -- less than, with dot
    [0x22D7] = "rel", -- greater than, with dot
    [0x22D8] = "rel", -- /ll /lll /llless r: triple less-than
    [0x22D9] = "rel", -- /ggg /gg /gggtr r: triple greater-than
    [0x22DA] = "rel", -- less, equals, greater
    [0x22DB] = "rel", -- greater, equals, less
    [0x22DC] = "rel", -- equal-or-less
    [0x22DD] = "rel", -- equal-or-greater
    [0x22DE] = "rel", -- curly equals, precedes
    [0x22DF] = "rel", -- curly equals, succeeds
    [0x22E0] = "rel", -- not precedes, curly equals
    [0x22E1] = "rel", -- not succeeds, curly equals
    [0x22E2] = "rel", -- not, square subset, equals
    [0x22E3] = "rel", -- not, square superset, equals
    [0x22E4] = "rel", -- square subset, not equals
    [0x22E5] = "rel", -- square superset, not equals
    [0x22E6] = "rel", -- less, not similar
    [0x22E7] = "rel", -- greater, not similar
    [0x22E8] = "rel", -- precedes, not similar
    [0x22E9] = "rel", -- succeeds, not similar
    [0x22EA] = "rel", -- not left triangle
    [0x22EB] = "rel", -- not right triangle
    [0x22EC] = "rel", -- not left triangle, equals
    [0x22ED] = "rel", -- not right triangle, equals
    [0x22EE] = "rel", -- vertical ellipsis
    [0x22F0] = "rel", -- three dots, ascending
    [0x22F1] = "rel", -- three dots, descending
    [0x22F2] = "rel", -- element of with long horizontal stroke
    [0x22F3] = "rel", -- element of with vertical bar at end of horizontal stroke
    [0x22F4] = "rel", -- small element of with vertical bar at end of horizontal stroke
    [0x22F5] = "rel", -- element of with dot above
    [0x22F6] = "rel", -- element of with overbar
    [0x22F7] = "rel", -- small element of with overbar
    [0x22F8] = "rel", -- element of with underbar
    [0x22F9] = "rel", -- element of with two horizontal strokes
    [0x22FA] = "rel", -- contains with long horizontal stroke
    [0x22FB] = "rel", -- contains with vertical bar at end of horizontal stroke
    [0x22FC] = "rel", -- small contains with vertical bar at end of horizontal stroke
    [0x22FD] = "rel", -- contains with overbar
    [0x22FE] = "rel", -- small contains with overbar
    [0x22FF] = "rel", -- z notation bag membership
    [0x2305] = "bin", -- /barwedge b: logical and, bar above [projective (bar over small wedge)]
    [0x2306] = "bin", -- /doublebarwedge b: logical and, double bar above [perspective (double bar over small wedge)]
    [0x2308] = "open", -- left ceiling
    [0x2309] = "close", -- right ceiling
    [0x230A] = "open", -- left floor
    [0x230B] = "close", -- right floor
    [0x231C] = "open", -- upper left corner
    [0x231D] = "close", -- upper right corner
    [0x231E] = "open", -- lower left corner
    [0x231F] = "close", -- lower right corner
    [0x2322] = "rel", -- down curve
    [0x2323] = "rel", -- up curve
    [0x233D] = "bin", -- circle with vertical bar
    [0x233F] = "rel", -- solidus, bar through (apl functional symbol slash bar)
    [0x23B0] = "open", -- upper left or lower right curly bracket section
    [0x23B1] = "close", -- upper right or lower left curly bracket section
    [0x23B4] = "over", -- top square bracket
    [0x23B5] = "under", -- bottom square bracket
    [0x23DC] = "over", -- top parenthesis (mathematical use)
    [0x23DD] = "under", -- bottom parenthesis (mathematical use)
    [0x23DE] = "over", -- top curly bracket (mathematical use)
    [0x23DF] = "under", -- bottom curly bracket (mathematical use)
    [0x25B3] = "bin", -- big up triangle, open
    [0x25B5] = "rel", -- /triangle - up triangle, open
    [0x25B7] = "bin", -- (large) right triangle, open; z notation range restriction
    [0x25C1] = "bin", -- (large) left triangle, open; z notation domain restriction
    [0x25CB] = "bin", -- medium large circle
    [0x25EB] = "bin", -- vertical bar in box
    [0x2772] = "open", -- light left tortoise shell bracket ornament
    [0x2773] = "close", -- light right tortoise shell bracket ornament
    [0x27C2] = "rel", -- perpendicular
    [0x27C5] = "open", -- left s-shaped bag delimiter
    [0x27C6] = "close", -- right s-shaped bag delimiter
    [0x27C7] = "bin", -- or with dot inside
    [0x27C8] = "rel", -- reverse solidus preceding subset
    [0x27C9] = "rel", -- superset preceding solidus
    [0x27CC] = "open", -- long division
    [0x27D1] = "bin", -- and with dot
    [0x27D2] = "rel", -- element of opening upwards
    [0x27D3] = "rel", -- lower right corner with dot
    [0x27D4] = "rel", -- upper left corner with dot
    [0x27D5] = "op", -- left outer join
    [0x27D6] = "op", -- right outer join
    [0x27D7] = "op", -- full outer join
    [0x27D8] = "op", -- large up tack
    [0x27D9] = "op", -- large down tack
    [0x27DA] = "rel", -- left and right double turnstile
    [0x27DB] = "rel", -- left and right tack
    [0x27DC] = "rel", -- left multimap
    [0x27DD] = "rel", -- long left tack
    [0x27DE] = "rel", -- long right tack
    [0x27DF] = "rel", -- up tack with circle above
    [0x27E0] = "bin", -- lozenge divided by horizontal rule
    [0x27E1] = "bin", -- white concave-sided diamond
    [0x27E2] = "bin", -- white concave-sided diamond with leftwards tick
    [0x27E3] = "bin", -- white concave-sided diamond with rightwards tick
    [0x27E4] = "bin", -- white square with leftwards tick
    [0x27E5] = "bin", -- white square with rightwards tick
    [0x27E6] = "open", -- mathematical left white square bracket
    [0x27E7] = "close", -- mathematical right white square bracket
    [0x27E8] = "open", -- mathematical left angle bracket
    [0x27E9] = "close", -- mathematical right angle bracket
    [0x27EA] = "open", -- mathematical left double angle bracket
    [0x27EB] = "close", -- mathematical right double angle bracket
    [0x27EC] = "open", -- mathematical left white tortoise shell bracket
    [0x27ED] = "close", -- mathematical right white tortoise shell bracket
    [0x27EE] = "open", -- mathematical left flattened parenthesis
    [0x27EF] = "close", -- mathematical right flattened parenthesis
    [0x27F0] = "rel", -- upwards quadruple arrow
    [0x27F1] = "rel", -- downwards quadruple arrow
    [0x27F2] = "rel", -- anticlockwise gapped circle arrow
    [0x27F3] = "rel", -- clockwise gapped circle arrow
    [0x27F4] = "rel", -- right arrow with circled plus
    [0x27F5] = "rel", -- long leftwards arrow
    [0x27F6] = "rel", -- long rightwards arrow
    [0x27F7] = "rel", -- long left right arrow
    [0x27F8] = "rel", -- long leftwards double arrow
    [0x27F9] = "rel", -- long rightwards double arrow
    [0x27FA] = "rel", -- long left right double arrow
    [0x27FB] = "rel", -- long leftwards arrow from bar
    [0x27FC] = "rel", -- long rightwards arrow from bar
    [0x27FD] = "rel", -- long leftwards double arrow from bar
    [0x27FE] = "rel", -- long rightwards double arrow from bar
    [0x27FF] = "rel", -- long rightwards squiggle arrow
    [0x2900] = "rel", -- rightwards two-headed arrow with vertical stroke
    [0x2901] = "rel", -- rightwards two-headed arrow with double vertical stroke
    [0x2902] = "rel", -- leftwards double arrow with vertical stroke
    [0x2903] = "rel", -- rightwards double arrow with vertical stroke
    [0x2904] = "rel", -- left right double arrow with vertical stroke
    [0x2905] = "rel", -- rightwards two-headed arrow from bar
    [0x2906] = "rel", -- leftwards double arrow from bar
    [0x2907] = "rel", -- rightwards double arrow from bar
    [0x2908] = "rel", -- downwards arrow with horizontal stroke
    [0x2909] = "rel", -- upwards arrow with horizontal stroke
    [0x290A] = "rel", -- upwards triple arrow
    [0x290B] = "rel", -- downwards triple arrow
    [0x290C] = "rel", -- leftwards double dash arrow
    [0x290D] = "rel", -- rightwards double dash arrow
    [0x290E] = "rel", -- leftwards triple dash arrow
    [0x290F] = "rel", -- rightwards triple dash arrow
    [0x2910] = "rel", -- rightwards two-headed triple dash arrow
    [0x2911] = "rel", -- rightwards arrow with dotted stem
    [0x2912] = "rel", -- upwards arrow to bar
    [0x2913] = "rel", -- downwards arrow to bar
    [0x2914] = "rel", -- rightwards arrow with tail with vertical stroke
    [0x2915] = "rel", -- rightwards arrow with tail with double vertical stroke
    [0x2916] = "rel", -- rightwards two-headed arrow with tail
    [0x2917] = "rel", -- rightwards two-headed arrow with tail with vertical stroke
    [0x2918] = "rel", -- rightwards two-headed arrow with tail with double vertical stroke
    [0x2919] = "rel", -- leftwards arrow-tail
    [0x291A] = "rel", -- rightwards arrow-tail
    [0x291B] = "rel", -- leftwards double arrow-tail
    [0x291C] = "rel", -- rightwards double arrow-tail
    [0x291D] = "rel", -- leftwards arrow to black diamond
    [0x291E] = "rel", -- rightwards arrow to black diamond
    [0x291F] = "rel", -- leftwards arrow from bar to black diamond
    [0x2920] = "rel", -- rightwards arrow from bar to black diamond
    [0x2921] = "rel", -- north west and south east arrow
    [0x2922] = "rel", -- north east and south west arrow
    [0x2923] = "rel", -- north west arrow with hook
    [0x2924] = "rel", -- north east arrow with hook
    [0x2925] = "rel", -- south east arrow with hook
    [0x2926] = "rel", -- south west arrow with hook
    [0x2927] = "rel", -- north west arrow and north east arrow
    [0x2928] = "rel", -- north east arrow and south east arrow
    [0x2929] = "rel", -- south east arrow and south west arrow
    [0x292A] = "rel", -- south west arrow and north west arrow
    [0x2933] = "rel", -- wave arrow pointing directly right
    [0x2936] = "rel", -- arrow pointing downwards then curving leftwards
    [0x2937] = "rel", -- arrow pointing downwards then curving rightwards
    [0x2938] = "rel", -- right-side arc clockwise arrow
    [0x2939] = "rel", -- left-side arc anticlockwise arrow
    [0x293A] = "rel", -- top arc anticlockwise arrow
    [0x293B] = "rel", -- bottom arc anticlockwise arrow
    [0x293C] = "rel", -- top arc clockwise arrow with minus
    [0x293D] = "rel", -- top arc anticlockwise arrow with plus
    [0x293E] = "rel", -- lower right semicircular clockwise arrow
    [0x293F] = "rel", -- lower left semicircular anticlockwise arrow
    [0x2940] = "rel", -- anticlockwise closed circle arrow
    [0x2941] = "rel", -- clockwise closed circle arrow
    [0x2942] = "rel", -- rightwards arrow above short leftwards arrow
    [0x2943] = "rel", -- leftwards arrow above short rightwards arrow
    [0x2944] = "rel", -- short rightwards arrow above leftwards arrow
    [0x2945] = "rel", -- rightwards arrow with plus below
    [0x2946] = "rel", -- leftwards arrow with plus below
    [0x2947] = "rel", -- rightwards arrow through x
    [0x2948] = "rel", -- left right arrow through small circle
    [0x2949] = "rel", -- upwards two-headed arrow from small circle
    [0x294A] = "rel", -- left barb up right barb down harpoon
    [0x294B] = "rel", -- left barb down right barb up harpoon
    [0x294C] = "rel", -- up barb right down barb left harpoon
    [0x294D] = "rel", -- up barb left down barb right harpoon
    [0x294E] = "rel", -- left barb up right barb up harpoon
    [0x294F] = "rel", -- up barb right down barb right harpoon
    [0x2950] = "rel", -- left barb down right barb down harpoon
    [0x2951] = "rel", -- up barb left down barb left harpoon
    [0x2952] = "rel", -- leftwards harpoon with barb up to bar
    [0x2953] = "rel", -- rightwards harpoon with barb up to bar
    [0x2954] = "rel", -- upwards harpoon with barb right to bar
    [0x2955] = "rel", -- downwards harpoon with barb right to bar
    [0x2956] = "rel", -- leftwards harpoon with barb down to bar
    [0x2957] = "rel", -- rightwards harpoon with barb down to bar
    [0x2958] = "rel", -- upwards harpoon with barb left to bar
    [0x2959] = "rel", -- downwards harpoon with barb left to bar
    [0x295A] = "rel", -- leftwards harpoon with barb up from bar
    [0x295B] = "rel", -- rightwards harpoon with barb up from bar
    [0x295C] = "rel", -- upwards harpoon with barb right from bar
    [0x295D] = "rel", -- downwards harpoon with barb right from bar
    [0x295E] = "rel", -- leftwards harpoon with barb down from bar
    [0x295F] = "rel", -- rightwards harpoon with barb down from bar
    [0x2960] = "rel", -- upwards harpoon with barb left from bar
    [0x2961] = "rel", -- downwards harpoon with barb left from bar
    [0x2962] = "rel", -- leftwards harpoon with barb up above leftwards harpoon with barb down
    [0x2963] = "rel", -- upwards harpoon with barb left beside upwards harpoon with barb right
    [0x2964] = "rel", -- rightwards harpoon with barb up above rightwards harpoon with barb down
    [0x2965] = "rel", -- downwards harpoon with barb left beside downwards harpoon with barb right
    [0x2966] = "rel", -- leftwards harpoon with barb up above rightwards harpoon with barb up
    [0x2967] = "rel", -- leftwards harpoon with barb down above rightwards harpoon with barb down
    [0x2968] = "rel", -- rightwards harpoon with barb up above leftwards harpoon with barb up
    [0x2969] = "rel", -- rightwards harpoon with barb down above leftwards harpoon with barb down
    [0x296A] = "rel", -- leftwards harpoon with barb up above long dash
    [0x296B] = "rel", -- leftwards harpoon with barb down below long dash
    [0x296C] = "rel", -- rightwards harpoon with barb up above long dash
    [0x296D] = "rel", -- rightwards harpoon with barb down below long dash
    [0x296E] = "rel", -- upwards harpoon with barb left beside downwards harpoon with barb right
    [0x296F] = "rel", -- downwards harpoon with barb left beside upwards harpoon with barb right
    [0x2970] = "rel", -- right double arrow with rounded head
    [0x2971] = "rel", -- equals sign above rightwards arrow
    [0x2972] = "rel", -- tilde operator above rightwards arrow
    [0x2973] = "rel", -- leftwards arrow above tilde operator
    [0x2974] = "rel", -- rightwards arrow above tilde operator
    [0x2975] = "rel", -- rightwards arrow above almost equal to
    [0x2976] = "rel", -- less-than above leftwards arrow
    [0x2977] = "rel", -- leftwards arrow through less-than
    [0x2978] = "rel", -- greater-than above rightwards arrow
    [0x2979] = "rel", -- subset above rightwards arrow
    [0x297A] = "rel", -- leftwards arrow through subset
    [0x297B] = "rel", -- superset above leftwards arrow
    [0x297C] = "rel", -- left fish tail
    [0x297D] = "rel", -- right fish tail
    [0x297E] = "rel", -- up fish tail
    [0x297F] = "rel", -- down fish tail
    [0x2980] = "fence", -- triple vertical bar delimiter
    [0x2982] = "rel", -- z notation type colon
    [0x2983] = "open", -- left white curly bracket
    [0x2984] = "close", -- right white curly bracket
    [0x2985] = "open", -- left white parenthesis
    [0x2986] = "close", -- right white parenthesis
    [0x2987] = "open", -- z notation left image bracket
    [0x2988] = "close", -- z notation right image bracket
    [0x2989] = "open", -- z notation left binding bracket
    [0x298A] = "close", -- z notation right binding bracket
    [0x298B] = "open", -- left square bracket with underbar
    [0x298C] = "close", -- right square bracket with underbar
    [0x298D] = "open", -- left square bracket with tick in top corner
    [0x298E] = "close", -- right square bracket with tick in bottom corner
    [0x298F] = "open", -- left square bracket with tick in bottom corner
    [0x2990] = "close", -- right square bracket with tick in top corner
    [0x2991] = "open", -- left angle bracket with dot
    [0x2992] = "close", -- right angle bracket with dot
    [0x2993] = "open", -- left arc less-than bracket
    [0x2994] = "close", -- right arc greater-than bracket
    [0x2995] = "open", -- double left arc greater-than bracket
    [0x2996] = "close", -- double right arc less-than bracket
    [0x2997] = "open", -- left black tortoise shell bracket
    [0x2998] = "close", -- right black tortoise shell bracket
    [0x29B5] = "bin", -- circle with horizontal bar
    [0x29B6] = "bin", -- circled vertical bar
    [0x29B7] = "bin", -- circled parallel
    [0x29B8] = "bin", -- circled reverse solidus
    [0x29B9] = "bin", -- circled perpendicular
    [0x29C0] = "bin", -- circled less-than
    [0x29C1] = "bin", -- circled greater-than
    [0x29C4] = "bin", -- squared rising diagonal slash
    [0x29C5] = "bin", -- squared falling diagonal slash
    [0x29C6] = "bin", -- squared asterisk
    [0x29C7] = "bin", -- squared small circle
    [0x29C8] = "bin", -- squared square
    [0x29CD] = "bin", -- triangle with serifs at bottom
    [0x29CE] = "rel", -- right triangle above left triangle
    [0x29CF] = "rel", -- left triangle beside vertical bar
    [0x29D0] = "rel", -- vertical bar beside right triangle
    [0x29D1] = "rel", -- left black bowtie
    [0x29D2] = "rel", -- right black bowtie
    [0x29D3] = "rel", -- black bowtie
    [0x29D4] = "rel", -- left black times
    [0x29D5] = "rel", -- right black times
    [0x29D6] = "bin", -- white hourglass
    [0x29D7] = "bin", -- black hourglass
    [0x29D8] = "open", -- left wiggly fence
    [0x29D9] = "close", -- right wiggly fence
    [0x29DA] = "open", -- left double wiggly fence
    [0x29DB] = "close", -- right double wiggly fence
    [0x29DF] = "rel", -- double-ended multimap
    [0x29E1] = "rel", -- increases as
    [0x29E2] = "bin", -- shuffle product
    [0x29E3] = "rel", -- equals sign and slanted parallel
    [0x29E4] = "rel", -- equals sign and slanted parallel with tilde above
    [0x29E5] = "rel", -- identical to and slanted parallel
    [0x29E6] = "rel", -- gleich stark
    [0x29EB] = "bin", -- black lozenge
    [0x29F4] = "rel", -- rule-delayed
    [0x29F5] = "bin", -- reverse solidus operator
    [0x29F6] = "bin", -- solidus with overbar
    [0x29F7] = "bin", -- reverse solidus with horizontal stroke
    [0x29F8] = "op", -- big solidus
    [0x29F9] = "op", -- big reverse solidus
    [0x29FA] = "bin", -- double plus
    [0x29FB] = "bin", -- triple plus
    [0x29FC] = "open", -- left pointing curved angle bracket
    [0x29FD] = "close", -- right pointing curved angle bracket
    [0x29FE] = "bin", -- tiny
    [0x29FF] = "bin", -- miny
    [0x2A00] = "op", -- n-ary circled dot operator
    [0x2A01] = "op", -- n-ary circled plus operator
    [0x2A02] = "op", -- n-ary circled times operator
    [0x2A03] = "op", -- n-ary union operator with dot
    [0x2A04] = "op", -- n-ary union operator with plus
    [0x2A05] = "op", -- n-ary square intersection operator
    [0x2A06] = "op", -- n-ary square union operator
    [0x2A07] = "op", -- two logical and operator
    [0x2A08] = "op", -- two logical or operator
    [0x2A09] = "op", -- n-ary times operator
    [0x2A0A] = "op", -- modulo two sum
    [0x2A0B] = "opnolimits", -- summation with integral
    [0x2A0C] = "opnolimits", -- quadruple integral operator
    [0x2A0D] = "opnolimits", -- finite part integral
    [0x2A0E] = "opnolimits", -- integral with double stroke
    [0x2A0F] = "opnolimits", -- integral average with slash
    [0x2A10] = "opnolimits", -- circulation function
    [0x2A11] = "opnolimits", -- anticlockwise integration
    [0x2A12] = "opnolimits", -- line integration with rectangular path around pole
    [0x2A13] = "opnolimits", -- line integration with semicircular path around pole
    [0x2A14] = "opnolimits", -- line integration not including the pole
    [0x2A15] = "opnolimits", -- integral around a point operator
    [0x2A16] = "opnolimits", -- quaternion integral operator
    [0x2A17] = "opnolimits", -- integral with leftwards arrow with hook
    [0x2A18] = "opnolimits", -- integral with times sign
    [0x2A19] = "opnolimits", -- integral with intersection
    [0x2A1A] = "opnolimits", -- integral with union
    [0x2A1B] = "opnolimits", -- integral with overbar
    [0x2A1C] = "opnolimits", -- integral with underbar
    [0x2A1D] = "op", -- join
    [0x2A1E] = "op", -- large left triangle operator
    [0x2A1F] = "op", -- z notation schema composition
    [0x2A20] = "op", -- z notation schema piping
    [0x2A21] = "op", -- z notation schema projection
    [0x2A22] = "bin", -- plus sign with small circle above
    [0x2A23] = "bin", -- plus sign with circumflex accent above
    [0x2A24] = "bin", -- plus sign with tilde above
    [0x2A25] = "bin", -- plus sign with dot below
    [0x2A26] = "bin", -- plus sign with tilde below
    [0x2A27] = "bin", -- plus sign with subscript two
    [0x2A28] = "bin", -- plus sign with black triangle
    [0x2A29] = "bin", -- minus sign with comma above
    [0x2A2A] = "bin", -- minus sign with dot below
    [0x2A2B] = "bin", -- minus sign with falling dots
    [0x2A2C] = "bin", -- minus sign with rising dots
    [0x2A2D] = "bin", -- plus sign in left half circle
    [0x2A2E] = "bin", -- plus sign in right half circle
    [0x2A2F] = "bin", -- vector or cross product
    [0x2A30] = "bin", -- multiplication sign with dot above
    [0x2A31] = "bin", -- multiplication sign with underbar
    [0x2A32] = "bin", -- semidirect product with bottom closed
    [0x2A33] = "bin", -- smash product
    [0x2A34] = "bin", -- multiplication sign in left half circle
    [0x2A35] = "bin", -- multiplication sign in right half circle
    [0x2A36] = "bin", -- circled multiplication sign with circumflex accent
    [0x2A37] = "bin", -- multiplication sign in double circle
    [0x2A38] = "bin", -- circled division sign
    [0x2A39] = "bin", -- plus sign in triangle
    [0x2A3A] = "bin", -- minus sign in triangle
    [0x2A3B] = "bin", -- multiplication sign in triangle
    [0x2A3C] = "bin", -- interior product
    [0x2A3D] = "bin", -- righthand interior product
    [0x2A3E] = "bin", -- z notation relational composition
    [0x2A3F] = "bin", -- amalgamation or coproduct
    [0x2A40] = "bin", -- intersection with dot
    [0x2A41] = "bin", -- union with minus sign
    [0x2A42] = "bin", -- union with overbar
    [0x2A43] = "bin", -- intersection with overbar
    [0x2A44] = "bin", -- intersection with logical and
    [0x2A45] = "bin", -- union with logical or
    [0x2A46] = "bin", -- union above intersection
    [0x2A47] = "bin", -- intersection above union
    [0x2A48] = "bin", -- union above bar above intersection
    [0x2A49] = "bin", -- intersection above bar above union
    [0x2A4A] = "bin", -- union beside and joined with union
    [0x2A4B] = "bin", -- intersection beside and joined with intersection
    [0x2A4C] = "bin", -- closed union with serifs
    [0x2A4D] = "bin", -- closed intersection with serifs
    [0x2A4E] = "bin", -- double square intersection
    [0x2A4F] = "bin", -- double square union
    [0x2A50] = "bin", -- closed union with serifs and smash product
    [0x2A51] = "bin", -- logical and with dot above
    [0x2A52] = "bin", -- logical or with dot above
    [0x2A53] = "bin", -- double logical and
    [0x2A54] = "bin", -- double logical or
    [0x2A55] = "bin", -- two intersecting logical and
    [0x2A56] = "bin", -- two intersecting logical or
    [0x2A57] = "bin", -- sloping large or
    [0x2A58] = "bin", -- sloping large and
    [0x2A59] = "rel", -- logical or overlapping logical and
    [0x2A5A] = "bin", -- logical and with middle stem
    [0x2A5B] = "bin", -- logical or with middle stem
    [0x2A5C] = "bin", -- ogical and with horizontal dash
    [0x2A5D] = "bin", -- logical or with horizontal dash
    [0x2A5E] = "bin", -- logical and with double overbar
    [0x2A5F] = "bin", -- logical and with underbar
    [0x2A60] = "bin", -- logical and with double underbar
    [0x2A61] = "bin", -- small vee with underbar
    [0x2A62] = "bin", -- logical or with double overbar
    [0x2A63] = "bin", -- logical or with double underbar
    [0x2A64] = "bin", -- z notation domain antirestriction
    [0x2A65] = "bin", -- z notation range antirestriction
    [0x2A66] = "rel", -- equals sign with dot below
    [0x2A67] = "rel", -- identical with dot above
    [0x2A68] = "rel", -- triple horizontal bar with double vertical stroke
    [0x2A69] = "rel", -- triple horizontal bar with triple vertical stroke
    [0x2A6A] = "rel", -- tilde operator with dot above
    [0x2A6B] = "rel", -- tilde operator with rising dots
    [0x2A6C] = "rel", -- similar minus similar
    [0x2A6D] = "rel", -- congruent with dot above
    [0x2A6E] = "rel", -- equals with asterisk
    [0x2A6F] = "rel", -- almost equal to with circumflex accent
    [0x2A70] = "rel", -- approximately equal or equal to
    [0x2A71] = "bin", -- equals sign above plus sign
    [0x2A72] = "bin", -- plus sign above equals sign
    [0x2A73] = "rel", -- equals sign above tilde operator
    [0x2A74] = "rel", -- double colon equal
    [0x2A75] = "rel", -- two consecutive equals signs
    [0x2A76] = "rel", -- three consecutive equals signs
    [0x2A77] = "rel", -- equals sign with two dots above and two dots below
    [0x2A78] = "rel", -- equivalent with four dots above
    [0x2A79] = "rel", -- less-than with circle inside
    [0x2A7A] = "rel", -- greater-than with circle inside
    [0x2A7B] = "rel", -- less-than with question mark above
    [0x2A7C] = "rel", -- greater-than with question mark above
    [0x2A7D] = "rel", -- less-than or slanted equal to
    [0x2A7E] = "rel", -- greater-than or slanted equal to
    [0x2A7F] = "rel", -- less-than or slanted equal to with dot inside
    [0x2A80] = "rel", -- greater-than or slanted equal to with dot inside
    [0x2A81] = "rel", -- less-than or slanted equal to with dot above
    [0x2A82] = "rel", -- greater-than or slanted equal to with dot above
    [0x2A83] = "rel", -- less-than or slanted equal to with dot above right
    [0x2A84] = "rel", -- greater-than or slanted equal to with dot above left
    [0x2A85] = "rel", -- less-than or approximate
    [0x2A86] = "rel", -- greater-than or approximate
    [0x2A87] = "rel", -- less-than and single-line not equal to
    [0x2A88] = "rel", -- greater-than and single-line not equal to
    [0x2A89] = "rel", -- less-than and not approximate
    [0x2A8A] = "rel", -- greater-than and not approximate
    [0x2A8B] = "rel", -- less-than above double-line equal above greater-than
    [0x2A8C] = "rel", -- greater-than above double-line equal above less-than
    [0x2A8D] = "rel", -- less-than above similar or equal
    [0x2A8E] = "rel", -- greater-than above similar or equal
    [0x2A8F] = "rel", -- less-than above similar above greater-than
    [0x2A90] = "rel", -- greater-than above similar above less-than
    [0x2A91] = "rel", -- less-than above greater-than above double-line equal
    [0x2A92] = "rel", -- greater-than above less-than above double-line equal
    [0x2A93] = "rel", -- less-than above slanted equal above greater-than above slanted equal
    [0x2A94] = "rel", -- greater-than above slanted equal above less-than above slanted equal
    [0x2A95] = "rel", -- slanted equal to or less-than
    [0x2A96] = "rel", -- slanted equal to or greater-than
    [0x2A97] = "rel", -- slanted equal to or less-than with dot inside
    [0x2A98] = "rel", -- slanted equal to or greater-than with dot inside
    [0x2A99] = "rel", -- double-line equal to or less-than
    [0x2A9A] = "rel", -- double-line equal to or greater-than
    [0x2A9B] = "rel", -- double-line slanted equal to or less-than
    [0x2A9C] = "rel", -- double-line slanted equal to or greater-than
    [0x2A9D] = "rel", -- similar or less-than
    [0x2A9E] = "rel", -- similar or greater-than
    [0x2A9F] = "rel", -- similar above less-than above equals sign
    [0x2AA0] = "rel", -- similar above greater-than above equals sign
    [0x2AA1] = "rel", -- double nested less-than
    [0x2AA2] = "rel", -- double nested greater-than
    [0x2AA3] = "rel", -- double less-than with underbar
    [0x2AA4] = "rel", -- greater-than overlapping less-than
    [0x2AA5] = "rel", -- greater-than beside less-than
    [0x2AA6] = "rel", -- less-than closed by curve
    [0x2AA7] = "rel", -- greater-than closed by curve
    [0x2AA8] = "rel", -- less-than closed by curve above slanted equal
    [0x2AA9] = "rel", -- greater-than closed by curve above slanted equal
    [0x2AAA] = "rel", -- smaller than
    [0x2AAB] = "rel", -- larger than
    [0x2AAC] = "rel", -- smaller than or equal to
    [0x2AAD] = "rel", -- larger than or equal to
    [0x2AAE] = "rel", -- equals sign with bumpy above
    [0x2AAF] = "rel", -- precedes above single-line equals sign
    [0x2AB0] = "rel", -- succeeds above single-line equals sign
    [0x2AB1] = "rel", -- precedes above single-line not equal to
    [0x2AB2] = "rel", -- succeeds above single-line not equal to
    [0x2AB3] = "rel", -- precedes above equals sign
    [0x2AB4] = "rel", -- succeeds above equals sign
    [0x2AB5] = "rel", -- precedes above not equal to
    [0x2AB6] = "rel", -- succeeds above not equal to
    [0x2AB7] = "rel", -- precedes above almost equal to
    [0x2AB8] = "rel", -- succeeds above almost equal to
    [0x2AB9] = "rel", -- precedes above not almost equal to
    [0x2ABA] = "rel", -- succeeds above not almost equal to
    [0x2ABB] = "rel", -- double precedes
    [0x2ABC] = "rel", -- double succeeds
    [0x2ABD] = "rel", -- subset with dot
    [0x2ABE] = "rel", -- superset with dot
    [0x2ABF] = "rel", -- subset with plus sign below
    [0x2AC0] = "rel", -- superset with plus sign below
    [0x2AC1] = "rel", -- subset with multiplication sign below
    [0x2AC2] = "rel", -- superset with multiplication sign below
    [0x2AC3] = "rel", -- subset of or equal to with dot above
    [0x2AC4] = "rel", -- superset of or equal to with dot above
    [0x2AC5] = "rel", -- subset of above equals sign
    [0x2AC6] = "rel", -- superset of above equals sign
    [0x2AC7] = "rel", -- subset of above tilde operator
    [0x2AC8] = "rel", -- superset of above tilde operator
    [0x2AC9] = "rel", -- subset of above almost equal to
    [0x2ACA] = "rel", -- superset of above almost equal to
    [0x2ACB] = "rel", -- subset of above not equal to
    [0x2ACC] = "rel", -- superset of above not equal to
    [0x2ACD] = "rel", -- square left open box operator
    [0x2ACE] = "rel", -- square right open box operator
    [0x2ACF] = "rel", -- closed subset
    [0x2AD0] = "rel", -- closed superset
    [0x2AD1] = "rel", -- closed subset or equal to
    [0x2AD2] = "rel", -- closed superset or equal to
    [0x2AD3] = "rel", -- subset above superset
    [0x2AD4] = "rel", -- superset above subset
    [0x2AD5] = "rel", -- subset above subset
    [0x2AD6] = "rel", -- superset above superset
    [0x2AD7] = "rel", -- superset beside subset
    [0x2AD8] = "rel", -- superset beside and joined by dash with subset
    [0x2AD9] = "rel", -- element of opening downwards
    [0x2ADA] = "rel", -- pitchfork with tee top
    [0x2ADB] = "rel", -- transversal intersection
    [0x2ADC] = "rel", -- forking
    [0x2ADD] = "rel", -- nonforking
    [0x2ADE] = "rel", -- short left tack
    [0x2ADF] = "rel", -- short down tack
    [0x2AE0] = "rel", -- short up tack
    [0x2AE2] = "rel", -- vertical bar triple right turnstile
    [0x2AE3] = "rel", -- double vertical bar left turnstile
    [0x2AE4] = "rel", -- vertical bar double left turnstile
    [0x2AE5] = "rel", -- double vertical bar double left turnstile
    [0x2AE6] = "rel", -- long dash from left member of double vertical
    [0x2AE7] = "rel", -- short down tack with overbar
    [0x2AE8] = "rel", -- short up tack with underbar
    [0x2AE9] = "rel", -- short up tack above short down tack
    [0x2AEA] = "rel", -- double down tack
    [0x2AEB] = "rel", -- double up tack
    [0x2AEC] = "rel", -- double stroke not sign
    [0x2AED] = "rel", -- reversed double stroke not sign
    [0x2AEE] = "rel", -- does not divide with reversed negation slash
    [0x2AEF] = "rel", -- vertical line with circle above
    [0x2AF0] = "rel", -- vertical line with circle below
    [0x2AF2] = "rel", -- parallel with horizontal stroke
    [0x2AF3] = "rel", -- parallel with tilde operator
    [0x2AF4] = "bin", -- triple vertical bar binary relation
    [0x2AF5] = "bin", -- triple vertical bar with horizontal stroke
    [0x2AF6] = "bin", -- triple colon operator
    [0x2AF7] = "rel", -- stacked very much less-than
    [0x2AF8] = "rel", -- stacked very much greater-than
    [0x2AF9] = "rel", -- double-line slanted less-than or equal to
    [0x2AFA] = "rel", -- double-line slanted greater-than or equal to
    [0x2AFB] = "bin", -- triple solidus binary relation
    [0x2AFC] = "op", -- large triple vertical bar operator
    [0x2AFD] = "bin", -- double solidus operator
    [0x2AFE] = "bin", -- white vertical bar
    [0x2AFF] = "op", -- n-ary white vertical bar
    [0x2B30] = "rel", -- left arrow with small circle
    [0x2B31] = "rel", -- three leftwards arrows
    [0x2B32] = "rel", -- left arrow with circled plus
    [0x2B33] = "rel", -- long leftwards squiggle arrow
    [0x2B34] = "rel", -- leftwards two-headed arrow with vertical stroke
    [0x2B35] = "rel", -- leftwards two-headed arrow with double vertical stroke
    [0x2B36] = "rel", -- leftwards two-headed arrow from bar
    [0x2B37] = "rel", -- leftwards two-headed triple-dash arrow
    [0x2B38] = "rel", -- leftwards arrow with dotted stem
    [0x2B39] = "rel", -- leftwards arrow with tail with vertical stroke
    [0x2B3A] = "rel", -- leftwards arrow with tail with double vertical stroke
    [0x2B3B] = "rel", -- leftwards two-headed arrow with tail
    [0x2B3C] = "rel", -- leftwards two-headed arrow with tail with vertical stroke
    [0x2B3D] = "rel", -- leftwards two-headed arrow with tail with double vertical stroke
    [0x2B3E] = "rel", -- leftwards arrow through x
    [0x2B3F] = "rel", -- wave arrow pointing directly left
    [0x2B40] = "rel", -- equals sign above leftwards arrow
    [0x2B41] = "rel", -- reverse tilde operator above leftwards arrow
    [0x2B42] = "rel", -- leftwards arrow above reverse almost equal to
    [0x2B43] = "rel", -- rightwards arrow through greater-than
    [0x2B44] = "rel", -- rightwards arrow through subset
    [0x2B45] = "rel", -- leftwards quadruple arrow
    [0x2B46] = "rel", -- rightwards quadruple arrow
    [0x2B47] = "rel", -- reverse tilde operator above rightwards arrow
    [0x2B48] = "rel", -- rightwards arrow above reverse almost equal to
    [0x2B49] = "rel", -- tilde operator above leftwards arrow
    [0x2B4A] = "rel", -- leftwards arrow above almost equal to
    [0x2B4B] = "rel", -- leftwards arrow above reverse tilde operator
    [0x2B4C] = "rel", -- righttwards arrow above reverse tilde operator
    [0x1EEF0] = "op", -- arabic mathematical operator meem with hah with tatweel
    [0x1EEF1] = "op", -- arabic mathematical operator hah with dal
}
