[appendix]
[[ch-installation,Installation]]
= Installationsanleitung
(((Installation)))

// == Versionen des Publishers



// == Installation

TIP: Den speedata Publisher kann man in zwei Versionen herunterladen: `stable` und `development`.
Beide Versionen sind problemlos zu benutzen.
Eine umfangreiche Qualitätssicherung verhindert, dass sich unentdeckt Fehler einschleichen.
In der Entwicklungsversion kann die Dokumentation dem aktuellen Stand hinterher sein.
Zum Ausprobieren lädt man sich in der Regel die Development-Version herunter.


Es gibt drei Methoden, den Publisher zu installieren.

. **Binärpakete** (der empfohlene Weg): Auf der https://download.speedata.de/[Download-Seite] (https://download.speedata.de/) sind für Mac, Linux und Windows ZIP-Dateien zu finden, die man einfach extrahieren kann.
Dafür sind keine Adminstratorrechte notwendig.
Für Windows gibt es zusätzlich Installationspakete, die den Suchpfad korrekt setzen.
Damit ist in der Windows-Shell das Programm `sp` überall aufrufbar.
 +
 +
Die aus dem ZIP extrahierte Struktur darf nicht verändert werden (z.B. verschieben des Binaries), der speedata Publisher erwartet das vorgegebene Dateilayout.
 +
Unter macOS 10.15 (Catalina) kommt es vor, dass das Sicherheitsfeature »Gatekeeper« für Ausführung des speedata Publishers eine spezielle Berechtigung anfordert. Das passiert, wenn die ZIP-Datei über einen Browser heruntergeladen wird. Um das zu umgehen, kann über die Kommandozeile mit `curl` der Publisher heruntergeladen werden:
+
-------------------------------------------------------------------------------
curl -O https://download.speedata.de/dl/speedata-publisher-darwin-amd64-latest.zip
-------------------------------------------------------------------------------
+
Das lädt die ZIP-Datei in das aktuelle Verzeichnis.



. **APT Repository**: Falls Administratorrechte auf einem Debian oder Ubuntu GNU/Linux System vorhanden sind, kann man einfach die `.deb`-Datei installieren. Hinweis: es wird bis auf weiteres nur die 64-Bit Plattform unterstützt.

.. Erstelle die Datei `/etc/apt/sources.list.d/speedata.list` mit dem Inhalt (Entwicklungsversion - development):
+
-------------------------------------------------------------------------------
deb https://software.speedata.de/download/devel stable main
-------------------------------------------------------------------------------
+
oder für die stabile Version:
+
-------------------------------------------------------------------------------
deb https://software.speedata.de/download/public stable main
-------------------------------------------------------------------------------

.. Füge den GPG-Schlüssel von uns hinzu, damit du sicherstellst, dass du immer die richtige Software bekommst:
+
-------------------------------------------------------------------------------
curl -O http://de.speedata.s3.amazonaws.com/gpgkey-speedata.txt
sudo apt-key add gpgkey-speedata.txt
-------------------------------------------------------------------------------

.. Nun kann man mit  `sudo apt update` und `sudo apt install speedata-publisher` den Publisher installieren.
Die Dokumentation befindet sich in `/usr/share/doc/speedata-publisher/index.html`, die mit `sp doc` auf einem Desktop-System geöffnet werden kann.

. **Aus den Quellen installieren**: Für die Entwickler, die am Publisher selbst Änderungen vornehmen möchten. Hierzu gibt es ein https://hub.docker.com/r/speedata/development[fertiges Docker-Image auf dockerhub]. Alternativ kann man die Software auch lokal bauen: sie aus dem Quellcode gebaut werden mithilfe des Befehls `rake` erstellt werden.
Notwendig dafür sind die üblichen Entwicklungswerkzeuge und die Programmiersprache Go (https://golang.org/) in Version 1.11 oder höher.
Auf einem Debian oder Ubuntu GNU/Linux System kann man folgende Befehle nutzen:
+
-------------------------------------------------------------------------------
sudo apt install build-essential git rake golang
git clone https://github.com/speedata/publisher.git
cd publisher
rake build
rake buildlib
-------------------------------------------------------------------------------
+
Um auch dieses Handbuch bzw. das ebook zu erstellen, werden https://asciidoctor.org/[asciidoctor], Java und https://gohugo.io/[Hugo] benötigt.
Damit werden auch etliche Abhängigkeiten installiert.
+
-------------------------------------------------------------------------------
sudo gem install asciidoctor
sudo apt install openjdk-11-jre
sudo snap install hugo
rake doc
-------------------------------------------------------------------------------
+
Falls der speedata Publisher aus den Quellen gebaut wird, muss noch LuaTeX hinzugefügt werden.
Der vorgeschlagene Weg ist, unter <https://download.speedata.de/#extra> die Binärpakete zu laden und das passende Paket in das bin-Verzeichnis zu kopieren.
Beispielsweise um LuajitTeX 1.10 auf einem Linux AMD64 System zu nutzen, kann man die folgenden Befehle ausführen:
+
-------------------------------------------------------------------------------
wget https://download.speedata.de/files/extra/luatex_110-win-mac-linux.zip
unzip luatex_110-win-mac-linux.zip
cp luatex/linux/amd64/1_10/sdluatex bin
-------------------------------------------------------------------------------
+
Nach der Installation kann man `bin/sdluatex --version` aufrufen, um zu überprüfen, ob es die richtige Version ist.

