[appendix]
[[ch-kommandozeile,Kommandozeile]]
= Starten des Publishers über die Kommandozeile

Der speedata Publisher wird über die Kommandozeile (auch: Terminal, Befehlsfenster) gestartet.
Einerseits gibt es _Befehle_, anderseits lassen sich die Befehle über _Parameter_ steuern.
Der Standardbefehl ist `run`. So ist der Aufruf von

[source,shell,subs="verbatim,quotes"]
-------------------------------------------------------------------------------
*$* sp
-------------------------------------------------------------------------------

dasselbe wie


[source,shell,subs="verbatim,quotes"]
-------------------------------------------------------------------------------
*$* sp run
-------------------------------------------------------------------------------

Neben dem Befehl `run` gibt es noch `clean`, `clearcache`, `compare`, `doc`, `list-fonts`, `server` und `watch`.
Diese sind weiter unten beschrieben.

Mit

[source, shell]
-------------------------------------------------------------------------------
$ sp --help
-------------------------------------------------------------------------------

kann man sich eine Liste der erlaubten Befehle und Parameter ausgeben lassen.


[[ch-cmd-erklaerung-parameter]]
== Erklärung der Kommandozeilenparameter

`--autoopen`::
   Öffnet die PDF-Datei nach dem Publisher-Durchlauf. Kann auch in der <<ch-konfiguration,Konfigurationsdatei>> eingestellt werden.
`--data=NAME`::
   Gibt den Namen der XML-Daten an. Voreinstellung ist `data.xml`. Wird als Dateiname ein Strich (`-`) angegeben, liest der Publisher die XML-Daten aus der Standard-Eingabe (STDIN).
`--cache=METHOD` ::
   Caching-Strategie für http(s) Bilddateien. Entweder `fast`, dann wird nur geschaut, ob die Bilddatei im Dateisystem vorhanden ist oder `optimal` (Voreinstellung), dann wird bei jedem Zugriff auf das Bild geprüft, ob das Bild aktualisiert werden muss. `https`-Requests werden derzeit mit der `optimal`-Strategie verwaltet.
`--cutmarks` ::
   Zeigt die Schnittmarken an. Einstellbar im <<cmd-options,Layout (Befehl Options)>>.
`--dummy`::
   Führt nur das Layoutregelwerk aus. Als Dateninhalt wird `<data />` angenommen. Dient zum schnellen Testen von Layoutregelwerken.
`-x`, `--extra-dir`::
   Bindet zusätzliche Verzeichnisse in den Publisherlauf ein. In diesen  Verzeichnissen werden alle Daten gesucht: Bilddaten, Layoutregelwerke,  Datendateien und Schriftdateien. Dieses Argument kann mehrfach  angegeben werden und per Konfigurationsdatei mit Werten vorbelegt werden. Mehrere Verzeichnisse können auch in einem Parameter und mit den systemweiten Trenner (Semikolon für Windows und Doppelpunkt für alle anderen Betriebssysteme) getrennt angegeben werden.
`--extra-xml=NAME` ::
   Diese Datei den Layoutanweisungen hinzufügen. Ähnlich wie das Einbinden einer Datei über xinclude. Mehrere Dateien werden mit Komma separiert.
`--filter=FILTER`::
   Führt die angegebene Lua-Datei aus. Siehe Kapitel <<luafilter>>.
`--grid`::
   Zeichnet das Raster. Mit `--no-grid` wird es ausgeschaltet. Konfigurierbar auch im <<cmd-trace,Layout>> über den Befehl `<Trace>`.
`--ignore-case`::
    Ignoriere die Groß- und Kleinschreibung für Dateizugriff.
`--layout=NAME`::
   Gibt den Namen des Layoutregelwerks an. Voreinstellung ist `layout.xml`.
`--local`::
   Das aktuelle Verzeichnis wird (nicht) rekursiv dem Suchpfad hinzugefügt. Voreingestellt ist, dass das aktuelle Verzeichnis und  seine Unterverzeichnisse beachtet werden.
`--jobname=NAME`::
   Bestimmt den Ausgabenamen. Voreinstellung ist `publisher`.
`--mainlanguage=NAME`::
   Bestimmt die Hauptsprache des Dokuments für die Silbentrennung. Mögliche Werte sind: `af`, `as`, `bg`, `ca`, `cs`, `cy`, `da`, `de`, `el`, `en`, `en_GB`, `en_US`, `eo`, `es`, `et`, `eu`, `fi`, `fr`,`ga`, `gl`, `gu`, `hi`, `hr`, `hu`, `hy`, `ia`, `id`, `is`, `it`,`ku`, `kn`, `la`, `lo`, `lt`, `ml`, `lv`, `ml`, `mn`, `mr`, `nb`, `nl`, `nn`, `or`, `pa`, `pl`, `pt`, `ro`, `ru`, `sa`, `sk`, `sl`,`sr`, `sv`, `ta`, `te`, `tk`, `tr`, `uk` und `zh`. Siehe http://www.loc.gov/standards/iso639-2/php/code_list.php[Codeliste der Sprachen].
`--outputdir=VERZEICHNIS`::
   Die resultierende PDF-Datei und Protokolldatei wird in das angegebene Verzeichnis kopiert. Das Verzeichnis wird erstellt, falls es noch nicht existiert.
`--profile`   ::
   Erzeugt Profiling-Informationen für den internen Gebrauch.
`--quiet`     ::
   Unterdrückt alle Ausgaben des Publishers.
`--runs = NUM`::
   Überschreibt die Anzahl der Durchläufe des Publishers.
`--startpage = NUM`::
   Die Seitennummer der ersten Seite.
`--show-gridallocation`::
   Markiert die belegten Rasterzellen in Gelb. Doppelt belegte Zellen werden rot gekennzeichnet. Siehe den <<cmd-trace,Befehl `<Trace>`>>.
`--systemfonts`::
   Lädt zusätzlich Systemschriftarten. Funktioniert nicht unter Windows XP.
`--tempdir` ::
   Benutze dieses Verzeichnis anstelle des Systemverzeichnisses für temporäre Dateien.
`--timeout=SEC`::
   Beendet den Lauf nach SEC Sekunden mit Statuscode 1, sofern er nicht vorher fertig ist.
`-v`, `--var=value`::
   Übergibt zusätzliche Variablen an den Publisher-Lauf. Diese können wie üblich mit `select="$variable"` benutzt werden.
`--varsfile=NAME` ::
   Liest eine Datei ein, in der in jeder Zeile in der Form `variable=wert` Variablen definiert werden.
`--verbose`::
   Gibt mehr Informationen aus, also notwendig.
`--wd=DIR`::
   Wechselt in das angegebene Verzeichnis. Verhält sich genau so, als ob man vorher mit cd in dieses Verzeichnis gewechselt hat.
`--xml`::
   Die Ausgabe des Befehls `list-fonts` werden als (Pseudo-)XML dargestellt, um sie in das Layoutregelwerk zu übernehmen.


[[ch-cmd-erklaerung-befehle]]
== Erklärung der Befehle

`clean`::
  Löscht alle generierten Zwischendateien und behält die PDF-Datei.
`clearcache`::
  Löscht den Bildcache.
`doc`::
  Öffnet das Referenzhandbuch im Browser (lokale HTML-Dateien).
`list-fonts`::
   Listet alle Schriftdateien auf, die in den Publisher-Verzeichnissen gefunden werden. Zusammen mit `--xml` erlaubt dieses Kommando die Ausgabe per Copy&Paste in das Layoutregelwerk zu übernehmen. Siehe <<ch-einbindungschriftarten>>.
`run`::
  Startet den Publisher Lauf. Das ist die Voreinstellung, so dass das Kommando `sp` reicht, um den Publikationsprozess zu starten.
`server`::
  Startet im Server-Modus. Siehe <<ch-servermodus,den Abschnitt Servermodus>>.
`watch`::
  Startet den internen Hotfolder. Siehe <<ch-hotfolder>>.


// Ende
