[[xprocfilter]]
= XProc-Filter

WARNING: Der XProc-Filter wird hier nur der Vollständigkeit halber beschreiben. Es ist unwahrscheinlich, dass er noch lange Bestand haben wird. Der neue <<luafilter,Lua-basierte Filter>> ist mächtiger und leichter zu programmieren.

XProc ist eine in XML formulierte Sprache, um Anweisungen hintereinander auszuführen.
Man kann es sich wie ein »In XML formuliertes« Make vorstellen, um verschiedene Dinge zu tun.
So könnte man eine XSLT-Transformation anstoßen, XML validieren oder Dateien kopieren.

Ein XProc-Filter um eine XSLT-Transformation anzustoßen sieht folgendermaßen aus:



[source, xml]
-------------------------------------------------------------------------------
<?xml version="1.0" encoding="UTF-8"?>
<p:declare-step xmlns:p="http://www.w3.org/ns/xproc"
    xmlns:c="http://www.w3.org/ns/xproc-step" version="1.0">
    <p:xslt name="Transformation">
        <p:input port="parameters">
            <p:empty/>
        </p:input>
        <p:input port="source">
            <p:document href="eingabedatei.xml"/>
        </p:input>
        <p:input port="stylesheet">
            <p:document href="transformation.xsl"/>
        </p:input>
    </p:xslt>
    <p:store href="data.xml"/>
</p:declare-step>
-------------------------------------------------------------------------------

Diese Instruktionen speichert man z. B. unter `filter.xpl`.

Die Syntax ist zwar etwas gewöhnungsbedürftig, aber durchaus erlernbar.
Der https://de.wikipedia.org/wiki/XProc[Wikipediaeintrag zu XProc] hilft hier weiter

Nun kann man mit


-------------------------------------------------------------------------------
sp --filter filter.xpl run
-------------------------------------------------------------------------------


den Publisher starten, während vorher einmalig die XProc-Anweisungen ausgeführt werden.


TIP: Mit XSLT kann man Daten oftmals leichter verarbeiten bzw. verändern als mit dem Publisher. Daher nutzt man in der Praxis den XProc-Filter, um vor einem Publisherlauf eine XSLT-Transformation automatisch auszuführen.

